location = /health {
    #opentelemetry-disabling-comment opentelemetry_operation_name '$request_method $request_uri';
    access_log off;
    default_type application/json;
    return 200 '{"status":"UP"}';
}

location = /probes/live {
    #opentelemetry-disabling-comment opentelemetry_operation_name '$request_method $request_uri';
    access_log off;
    default_type application/json;
    return 200 '{"status":"UP"}';
}

location = /probes/ready {
    #opentelemetry-disabling-comment opentelemetry_operation_name '$request_method $request_uri';
    access_log off;
    default_type application/json;
    return 200 '{"status":"UP"}';
}
