FROM alpine:3.23.0
LABEL maintainer="qubership"

RUN apk update --no-cache
RUN apk add --no-cache ca-certificates curl bash nss_wrapper
RUN apk add --no-cache --upgrade libcrypto3 libssl3

# temporary use of edge to fix CVE-2025-9086 remove on 3.23.-x release
RUN apk add --no-cache --upgrade curl --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main

ENV HOME=/app \
USER_NAME=appuser \
CERTIFICATE_FILE_LOCATION=/usr/local/share/ca-certificates

ENV LANG=en_US.UTF-8 \
LANGUAGE=en_US:en \
LC_ALL=en_US.UTF-8

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 && \
    mkdir -p /tmp/cert && \
    mkdir $HOME && \
    chmod g=u $HOME && \
    chown 10001:0 $HOME && \
    chmod ug+rw ${CERTIFICATE_FILE_LOCATION} && \
    chown 10001:0 ${CERTIFICATE_FILE_LOCATION} && \
    chmod ug+rw /etc/ssl/certs && \
    chown -R 10001:0 /etc/ssl/certs && \
    mkdir -p /app/init.d && \
    mkdir -p /app/nss && \
    chmod ug+rw -R /app/nss && \
    chown -R 10001:0 /app/nss && \
    mkdir -p /app/volumes/certs && \
    chmod ug+r -R /app/volumes/certs && \
    chown -R 10001:0 /app/volumes/certs && \
    cp -R /etc/ssl/certs /app/volumes && \
    chmod ug+r -R /app/volumes && \
    chown -R 10001:0 /app/volumes

USER 10001:10001

WORKDIR /app

COPY --chown=10001:0 --chmod=755 entrypoint.sh /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]
