services:
  service1:
    build: ./java-base/
    ports:
      - "8081:8080"
    environment:
      - SERVICE_NAME=service1
      - CERTIFICATE_FILE_PASSWORD=testit
      - TEST_URL=http://service2:8080/version
    volumes:
      - ./certs/:/tmp/cert/ 
    networks:
      - mynetwork
    stdin_open: true   

  service2:
    build: ./java-base/
    ports:
      - "8083:8080"
    environment:
      - SERVICE_NAME=service2
      - CERTIFICATE_FILE_PASSWORD=testit
      - TEST_URL=http://service1:8080/version
    volumes:
      - ./certs/:/tmp/cert/
    networks:
      - mynetwork
    stdin_open: true   

networks:
  mynetwork:
    driver: bridge