name: Build and Push Multi-Platform Docker Image

on:
  push:

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    steps:
    - id: tag
      run: | 
        echo "tag=$(echo ${{github.ref_name}} | tr -cs 'a-zA-Z0-9' '-')$(date +'%Y%m%d%H%M%S')-${{ github.run_number }}" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare-variables
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push core-image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/netcracker/qubership/core-base:${{ needs.prepare-variables.outputs.tag }}
            ghcr.io/netcracker/qubership/core-base:latest
          file: Dockerfile.base-alpine.amd64
          platforms: linux/amd64

      - name: Build and push java-image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/netcracker/qubership/java-base:${{ needs.prepare-variables.outputs.tag }}
            ghcr.io/netcracker/qubership/java-base:latest
          file: Dockerfile.java-alpine.amd64
          platforms: linux/amd64