name: Docker image publish

on:
  - push

jobs:
  datetime:
    name: Getting current date and time
    runs-on: ubuntu-latest
    steps:
      - id: datetime
        run: echo "value=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.datetime.outputs.value }}
  call-docker-publish:
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
    needs: [ datetime ]
    with:
      component: '[
                     {"name": "qubership-core.base-alpine.amd64-${{ needs.datetime.outputs.value }}", "file": "./Dockerfile.base-alpine.amd64"},
                     {"name": "qubership-core.java-alpine.amd64-${{ needs.datetime.outputs.value }}", "file": "./Dockerfile.java-alpine.amd64"}
                  ]'
