name: Build and Push Multi-Platform Docker Image

on:
  push:

jobs:
  datetime:
    name: Getting current date and time
    runs-on: ubuntu-latest
    steps:
      - id: datetime
        run: echo "value=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    outputs:
      value: ${{ steps.datetime.outputs.value }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [ datetime ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (для эмуляции других архитектур)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (для кроссплатформенной сборки)
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/netcracker/qubership/core-base:latest
          file: Dockerfile.base-alpine.amd64
          platforms: linux/amd64