---

name: "Add commit messages to PR body"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  update-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: "Update PR body"
        uses: netcracker/qubership-workflow-hub/actions/pr-add-messages@2c080173c1cda277aeedd67cb60148b5367aac68 # main
