---

name: "Add commit messages to PR body"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  update-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: "Update PR body"
        uses: netcracker/qubership-workflow-hub/actions/pr-add-messages@24c9f9bc6392a24ac68776a218c9d84fcd452b92 # main
